---
# handlers file for ossec-wazuh

- name: start ossec
  service: name=ossec
           state=started
           enabled=yes


- name: start httpd
  service: name=httpd
           state=started
           enabled=yes

